version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: install bundle
          command: docker-compose run api bundle install
      - run:
          name: start containers
          command: docker-compose up -d
      - run:
          name: check lint
          command: docker-compose run api bundle exec rubocop
      - run:
          name: test api
          command: docker-compose run api bundle exec rspec
      - run:
          name: shutdown container
          command: docker-compose down